version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_SCHEMA=github
    ports:
      - 5432:5432
    volumes:
      - ./db/pg-data:/var/lib/postgresql/data
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.3
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmial.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./db/pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

volumes:
  pg-data:
  pgadmin-data:


networks:
  postgres:
    driver: bridge
