version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    container_name: github-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_SCHEMA=github
    ports:
      - 5432:5432
    volumes:
      - ./db/pg-data:/var/lib/postgresql/data
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - postgres
  pgadmin:
    container_name: pg-admin
    image: dpage/pgadmin4:7.3
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmial.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./db/pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres
  dashboard:
    build:
      context: .
      dockerfile: ./src/dashboard/Dockerfile
    container_name: dashboard
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_SCHEMA=github
      - POSTGRES_HOST=github-db
    ports:
      - 8501:8501
    networks:
      - postgres
    depends_on:
      - db
volumes:
  pg-data:
  pgadmin-data:


networks:
  postgres:
    driver: bridge
